### ISSUE TITLE
crc-interactive.py not compatible with python3.6 on login nodes

### ISSUE THREAD

**Issue by Comeani** [pitt-crc/wrappers#17]
In an effort to fix an issue with python lmod module load order and move away from using the py_wrap scripts, #11 sets the interpreter to python3.6, ignoring PYTHONPATH and PYTHONHOME to properly run the script. 

Python3.6 on the login nodes, (and possible all of the compute nodes) **does not have docopt and errors on the import attempt**. 

The change that was made seems like a good choice to implement across other wrapper/admin python scripts that are otherwise relying on py_wrap (#15), but we should consider the version/environment for python we want the wrapper scripts to run in, and investigate a better way to keep that environment consistent and updated across all machines where they might be run before trying to standardize.

**Comment by djperrefort** [comment]
@Comeani I see there is a PR attached to this issue. Can this be closed?
