### ISSUE TITLE
Add support for Keystone-API

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/wrappers#229]
Usage data is currently pulled from the crc-bank. As we migrate to Keystone, usage data should be pulled from the Keystone REST API instead.

**Comment by Comeani** [comment]
`crc_proposal_end`, `crc_sus`, and `crc_usage` appear to be the only ones that are impacted. @chnixi If you've started on this at all somewhere, can you push your branch so it's available remotely? If not, I can create one and will start in on `crc_usage`.

**Comment by chnixi** [comment]
I haven't started yet, please feel free to create a new branch.

**Comment by Comeani** [comment]
All wrapper applications that absolutely need to pull info from keystone have been updated in #233. #231 remains open, but is more of an effort towards https://github.com/pitt-crc/keystone-api/issues/197 while that is not yet done.
