### ISSUE TITLE
crc-idle.py reports GPUs that are in drain state as idle

### ISSUE THREAD

**Issue by burntyellow** [pitt-crc/wrappers#6]
See the gtx1080 partition. When k40 was in drain state, it also reported the 2 GPUs as idle.

```
[kimwong@login1.crc.pitt.edu ~]$sinfo -M gpu
CLUSTER: gpu
PARTITION      AVAIL  TIMELIMIT  NODES  STATE NODELIST
gtx1080*          up   infinite      1  drain gpu-stage08
gtx1080*          up   infinite     16    mix gpu-n[16-25],gpu-stage[09-14]
titanx            up   infinite      7    mix gpu-stage[01-07]
k40               up   infinite      1   idle smpgpu-n0
isenocak          up   infinite      1   idle gpu-n26
v100              up   infinite      1    mix gpu-n27
isenocak-mpi      up   infinite      1    mix gpu-n27
isenocak-mpi      up   infinite      1   idle gpu-n26
eschneider        up   infinite      1   idle ppc-n0
power9            up   infinite      4   idle ppc-n[1-4]
eschneider-mpi    up   infinite      5   idle ppc-n[0-4]
scavenger         up   infinite      1  drain gpu-stage08
scavenger         up   infinite     24    mix gpu-n[16-25,27],gpu-stage[01-07,09-14]
scavenger         up   infinite      1   idle smpgpu-n0
a100              up   infinite      3    mix gpu-n[28-30]
[kimwong@login1.crc.pitt.edu ~]$crc-idle.py -g
Cluster: gpu, Partition: gtx1080
================================
  1 nodes w/   4 idle GPUs
Cluster: gpu, Partition: titanx
===============================
  1 nodes w/   2 idle GPUs
Cluster: gpu, Partition: k40
============================
  1 nodes w/   2 idle GPUs
Cluster: gpu, Partition: v100
=============================
  1 nodes w/   3 idle GPUs
[kimwong@login1.crc.pitt.edu ~]$
```

**Comment by Comeani** [comment]
I can't find any documentation on where sinfo pulls gresUsed from if you supply that as in my additions to #14, but this issue appears to persist:

Reporting gpu-stage08 as 4 total, 0 allocated:
`[nlc60@login0b ~] issue/16 : sinfo -h -M gpu -p gtx1080 -N --Format=NodeList:_,gres:5,gresUsed:12
...
gpu-stage08_gpu:4_gpu:(null):0_
...`
This would report as 1 node with 4 GPUs available.

Kim's sinfo reporting gpu-stage08 in drain:
`[nlc60@login0b ~] issue/16 : sinfo -M gpu -p gtx1080                            CLUSTER: gpu
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
gtx1080*     up   infinite      1  drain gpu-stage08
gtx1080*     up   infinite     16    mix gpu-n[16-25],gpu-stage[09-14]`

#14 resolves this if:
- the way sinfo determines gresUsed is accurate
- the STATE on the GPU compute nodes is in reference to the host CPUs, not the GPUs.

**Comment by Comeani** [comment]
My current guess is that gresUSED is computed from info from running jobs. 
`[nlc60@login0b Node-Nanny] issue/16 : sacct -a -X -M gpu --format=JobID,AllocGRES --state=RUNNING
       JobID    AllocGRES
------------ ------------
311836              gpu:1
312365              gpu:1
312590              gpu:1
312591              gpu:1
312592              gpu:1
312593              gpu:1
312594              gpu:1
312595              gpu:1
312600              gpu:1
312601              gpu:1
312891              gpu:1
312894              gpu:1
312916              gpu:1
312921              gpu:1
312926              gpu:1
312942              gpu:4
312954              gpu:1
312959              gpu:1
312964              gpu:1
312969              gpu:1
312980              gpu:1
312985              gpu:1
312990              gpu:1
312995              gpu:1
313000              gpu:1
313017              gpu:4
313019             gpu:16
313020              gpu:1
313021              gpu:1
313022              gpu:1
313028              gpu:1
313055              gpu:1
313056              gpu:1
313058              gpu:1
313059              gpu:1
313061              gpu:1
313069              gpu:1
313072              gpu:1
313073              gpu:1
313074              gpu:1
313075              gpu:1
313076              gpu:1
313077              gpu:1
313078              gpu:1
313079              gpu:1
313080              gpu:1
313081              gpu:1
313083              gpu:1
313084              gpu:1
313085              gpu:1
313086              gpu:1
313088              gpu:1
313089              gpu:1
313090              gpu:1
313091              gpu:1
313093              gpu:1
313094              gpu:1
313095              gpu:1
313096              gpu:1
313098              gpu:1
313099              gpu:1
313100              gpu:1
313101              gpu:1
313103              gpu:1
313104              gpu:1
313105              gpu:1
313106              gpu:1
313107              gpu:1
313108              gpu:1
313109              gpu:1
313110              gpu:1
313111              gpu:1
313113              gpu:1
313114              gpu:1
313115              gpu:1
313116              gpu:1
313118              gpu:1
313119              gpu:1
313120              gpu:1
313121              gpu:1
313122              gpu:1
313126              gpu:1
313127              gpu:1
313128              gpu:1
313130              gpu:1
313131              gpu:1
313132              gpu:1
313133              gpu:1
313135              gpu:1
313136              gpu:1
313137              gpu:1
313138              gpu:1
313142              gpu:1
313146              gpu:1
313147              gpu:1
313166              gpu:1
313186              gpu:1
313206              gpu:1`

And that the state is related to the host CPUS:
`nlc60@login0b]: sinfo -M gpu -NO nodelist:15,cpusstate:15,gres:14,gresused:12,statelong:.10
CLUSTER: gpu
NODELIST       CPUS(A/I/O/T)  GRES          GRES_USED        STATE
gpu-n16        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n16        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n17        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n17        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n18        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n18        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n19        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n19        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n20        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n20        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n21        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n21        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n22        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n22        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n23        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n23        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n24        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n24        4/4/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n25        5/3/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n25        5/3/0/8        gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-n26        0/24/0/24      gpu:4(S:0-1)  gpu:(null):0      idle
gpu-n26        0/24/0/24      gpu:4(S:0-1)  gpu:(null):0      idle
gpu-n27        2/22/0/24      gpu:4(S:0-1)  gpu:(null):2     mixed
gpu-n27        2/22/0/24      gpu:4(S:0-1)  gpu:(null):2     mixed
gpu-n27        2/22/0/24      gpu:4(S:0-1)  gpu:(null):2     mixed
gpu-n28        0/0/128/128    gpu:8(S:0-1)  gpu:(null):0   drained
gpu-n29        8/120/0/128    gpu:8(S:0-1)  gpu:(null):8     mixed
gpu-n30        4/124/0/128    gpu:8(S:0-1)  gpu:(null):4     mixed
gpu-stage01    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage01    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage02    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage02    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage03    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage03    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage04    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage04    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage05    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage05    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage06    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage06    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage07    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage07    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage08    0/0/12/12      gpu:4(S:0-1)  gpu:(null):0   drained
gpu-stage08    0/0/12/12      gpu:4(S:0-1)  gpu:(null):0   drained
gpu-stage09    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage09    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage10    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage10    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage11    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage11    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage12    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage12    4/8/0/12       gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage13    1/11/0/12      gpu:4(S:0-1)  gpu:(null):1     mixed
gpu-stage13    1/11/0/12      gpu:4(S:0-1)  gpu:(null):1     mixed
gpu-stage14    4/12/0/16      gpu:4(S:0-1)  gpu:(null):4     mixed
gpu-stage14    4/12/0/16      gpu:4(S:0-1)  gpu:(null):4     mixed
ppc-n0         4/124/0/128    gpu:4(S:0-1)  gpu:(null):4     mixed
ppc-n0         4/124/0/128    gpu:4(S:0-1)  gpu:(null):4     mixed
ppc-n1         4/124/0/128    gpu:4(S:0-1)  gpu:(null):4     mixed
ppc-n1         4/124/0/128    gpu:4(S:0-1)  gpu:(null):4     mixed
ppc-n2         4/124/0/128    gpu:4(S:0-1)  gpu:(null):4     mixed
ppc-n2         4/124/0/128    gpu:4(S:0-1)  gpu:(null):4     mixed
ppc-n3         4/124/0/128    gpu:4(S:0-1)  gpu:(null):4     mixed
ppc-n3         4/124/0/128    gpu:4(S:0-1)  gpu:(null):4     mixed
ppc-n4         0/128/0/128    gpu:4(S:0-1)  gpu:(null):0      idle
ppc-n4         0/128/0/128    gpu:4(S:0-1)  gpu:(null):0      idle
smpgpu-n0      0/20/0/20      gpu:2(S:0-1)  gpu:(null):0      idle
smpgpu-n0      0/20/0/20      gpu:2(S:0-1)  gpu:(null):0      idle`
